### ISSUE TITLE
Multiple tags in tag-list are ignored only last is respected

### ISSUE THREAD

**Issue by karolisc** [voxpupuli/puppet-gitlab_ci_runner#37]
## How to reproduce (e.g Puppet code you use)
Hiera code:
```
gitlab_ci_runner::runners:
  test_runner3:
    url: "https://git.alternative.org/ci"
    registration-token: "abcdef1234567890"
    tag-list:
      - tag1
      - tag2
```
## What are you seeing
gitlab-runner is created with the last tag in the list (tag2) only.

## What behaviour did you expect instead
Would expect to see all the tags in the list ( tag1 and tag2)

**Comment by surprisingb** [comment]
I don't think the `tag-list` parameter is managed as a proper array.
You could try to define the tags as a comma-separated list, the same way you'd do with the command line:

```
gitlab_ci_runner::runners:
  test_runner3:
    url: "https://git.alternative.org/ci"
    registration-token: "abcdef1234567890"
    tag-list: "tag1,tag2"
```
