### ISSUE TITLE
locked parameter declaration exception

### ISSUE THREAD

**Issue by karolisc** [voxpupuli/puppet-gitlab_ci_runner#38]
## How to reproduce (e.g Puppet code you use)
Hiera Code:
```
gitlab_ci_runner::runners:
  test_runner3:
    url: "https://git.alternative.org/ci"
    registration-token: "abcdef1234567890"
    locked: "false"
```

## What are you seeing
At the command line it is represented:
```
--locked "false"
```

## What behaviour did you expect instead
According to  https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/758
`Boolean values` must be declared with equal sign e.g. `--flag=x`

## Any additional information you'd like to impart
This does work but at the same time it's awful hack:
```
locked=false:
```
